In [1]:
import pandas as pd

In [2]:
transaction_history = pd.read_csv(
    "../data/transaction_history.csv", dtype={"customer_id": str}
)  # 顧客の購入履歴データ
product_master = pd.read_csv("../data/product_master.csv")  # 商品マスターのデータ

In [3]:
# transaction_historyとProduct_masterをproduct_idで結合（Left Join)し、marged_dataオブジェクトに格納
merged_data = transaction_history.merge(product_master, on="product_id", how="left")

In [4]:
# 結果の表示
merged_data.head()

,customer_id,product_id,purchase_date,purchase_amount,redeem_coupon,final_settlement_amount,payment_method,purchase_channel,product_name,product_type,price,departure_city,destination_city,register_date,description
0,00023085,G03257PD,2020/3/13,7200,True,6200.0,現金,2.0,サクラエアライン 東京 → バンコク 航空券（ビジネスクラス）,6.0,7200.0,東京,バンコク,2020/7/14,東京からバンコクまで、サクラエアラインのビジネスクラスで快適な空の旅を。上質なサービスで特別...
1,00015469,CKZF21ZC,2023/3/29,15400,False,NaN,カード,2.0,魅惑のローマ 6日間ツアー,3.0,15400.0,東京,ローマ,2023/3/13,ローマの魅力を存分に楽しめる6日間のツアー。魅惑の体験を満喫し、心に残る旅を。
2,00015482,7NSE0G0R,2023/12/26,15400,False,NaN,現金,1.0,ふじヴィラ（熊本）宿泊,5.0,15400.0,NaN,熊本,2020/3/26,ふじヴィラ（熊本）宿泊への滞在手配です。ふじヴィラ（熊本）宿泊で贅沢な時間を
3,00017107,WVCPYZBH,2021/2/19,17100,False,NaN,カード,2.0,夢のようなの香港 4日間ツアー,3.0,7200.0,大阪,香港,2020/8/31,香港の魅力を存分に楽しめる4日間のツアー。夢のようなな体験を満喫し、心に残る旅を。
4,00024156,OELTJ7E2,2020/10/8,24100,True,23100.0,カード,1.0,魅惑のドバイ 5日間ツアー,3.0,24100.0,東京,ドバイ,2020/2/5,ドバイの魅力を存分に楽しめる5日間のツアー。魅惑の体験を満喫し、心に残る旅を。

In [5]:
# marged_dataの行数と列数を確認
merged_data.shape

(458167, 15)

In [6]:
# Transaction_historyとProduct_masterをproduct_idで結合（Right JOIN)し、marged_data2オブジェクトに格納
merged_data2 = transaction_history.merge(product_master, on="product_id", how="right")

In [7]:
# 結果の表示
merged_data2.head()

,customer_id,product_id,purchase_date,purchase_amount,redeem_coupon,final_settlement_amount,payment_method,purchase_channel,product_name,product_type,price,departure_city,destination_city,register_date,description
0,00010011,8RBQ8O3I,2021/7/27,72100.0,False,NaN,現金,1.0,リラックスできるニューヨーク 6日間ツアー,3,72100.0,福岡,ニューヨーク,2023/8/28,ニューヨークの魅力を存分に楽しめる6日間のツアー。リラックスできる体験を満喫し、心に残る旅を。
1,NaN,ZFQK59UL,NaN,NaN,NaN,NaN,NaN,NaN,ドキドキの香港 5日間ツアー,3,NaN,京都,香港,2023/12/24,香港の魅力を存分に楽しめる5日間のツアー。ドキドキな体験を満喫し、心に残る旅を。
2,00010014,5YH8O89R,2023/7/6,8500.0,True,8075.0,現金,4.0,ジャパンウィング航空 東京 → 高松 航空券,2,8500.0,東京,高松,2024/9/5,東京から高松へ、ジャパンウィング航空で快適な国内旅行を。お得な航空券で気軽に旅に出かけましょう。
3,00010016,MQTY8P6S,2019/10/21,286100.0,False,NaN,現金,2.0,贅沢なドバイ 6日間ツアー,3,286100.0,東京,ドバイ,2024/10/29,ドバイの魅力を存分に楽しめる6日間のツアー。贅沢な体験を満喫し、心に残る旅を。
4,NaN,1FKCUCHP,NaN,NaN,NaN,NaN,NaN,NaN,贅沢なドバイ 8日間ツアー,3,235000.0,京都,ドバイ,2023/5/13,ドバイの魅力を存分に楽しめる8日間のツアー。贅沢な体験を満喫し、心に残る旅を。

In [8]:
# marged_data2の行数と列数を確認
merged_data2.shape

(317999, 15)

In [9]:
# transaction_historyとProduct_masterをproduct_idで結合（innner join)し、marged_data3オブジェクトに格納
merged_data3 = transaction_history.merge(product_master, on="product_id", how="inner")

In [10]:
# 結果の表示
merged_data3.head()

,customer_id,product_id,purchase_date,purchase_amount,redeem_coupon,final_settlement_amount,payment_method,purchase_channel,product_name,product_type,price,departure_city,destination_city,register_date,description
0,00023085,G03257PD,2020/3/13,7200,True,6200.0,現金,2.0,サクラエアライン 東京 → バンコク 航空券（ビジネスクラス）,6,7200.0,東京,バンコク,2020/7/14,東京からバンコクまで、サクラエアラインのビジネスクラスで快適な空の旅を。上質なサービスで特別...
1,00015469,CKZF21ZC,2023/3/29,15400,False,NaN,カード,2.0,魅惑のローマ 6日間ツアー,3,15400.0,東京,ローマ,2023/3/13,ローマの魅力を存分に楽しめる6日間のツアー。魅惑の体験を満喫し、心に残る旅を。
2,00015482,7NSE0G0R,2023/12/26,15400,False,NaN,現金,1.0,ふじヴィラ（熊本）宿泊,5,15400.0,NaN,熊本,2020/3/26,ふじヴィラ（熊本）宿泊への滞在手配です。ふじヴィラ（熊本）宿泊で贅沢な時間を
3,00017107,WVCPYZBH,2021/2/19,17100,False,NaN,カード,2.0,夢のようなの香港 4日間ツアー,3,7200.0,大阪,香港,2020/8/31,香港の魅力を存分に楽しめる4日間のツアー。夢のようなな体験を満喫し、心に残る旅を。
4,00024156,OELTJ7E2,2020/10/8,24100,True,23100.0,カード,1.0,魅惑のドバイ 5日間ツアー,3,24100.0,東京,ドバイ,2020/2/5,ドバイの魅力を存分に楽しめる5日間のツアー。魅惑の体験を満喫し、心に残る旅を。

In [11]:
# marged_data3の行数と列数を確認
merged_data3.shape

(179991, 15)