In [1]:
import pandas as pd

In [2]:
transaction_history = pd.read_csv(
    "../data/transaction_history.csv", dtype={"customer_id": str}
)  # 顧客の購入履歴データ
product_master = pd.read_csv("../data/product_master.csv")  # 商品マスターのデータ

In [3]:
# transaction_historyとProduct_masterをproduct_idで結合（Left Join)し、marged_dataオブジェクトに格納
merged_data = transaction_history.merge(product_master, on="product_id", how="left")

In [4]:
# 結果の表示
merged_data.head()

,customer_id,product_id,purchase_date,purchase_amount,redeem_coupon,final_settlement_amount,payment_method,purchase_channel,product_name,product_type,price,departure_city,destination_city,register_date,description
0,00023085,G03257PD,2020/3/13,7200,True,6200.0,現金,2.0,サクラエアライン 東京 → バンコク 航空券（ビジネスクラス）,6.0,7200.0,東京,バンコク,2020/7/14,東京からバンコクまで、サクラエアラインのビジネスクラスで快適な空の旅を。上質なサービスで特別...
1,00015469,CKZF21ZC,2023/3/29,15400,False,NaN,カード,2.0,魅惑のローマ 6日間ツアー,3.0,15400.0,東京,ローマ,2023/3/13,ローマの魅力を存分に楽しめる6日間のツアー。魅惑の体験を満喫し、心に残る旅を。
2,00015482,7NSE0G0R,2023/12/26,15400,False,NaN,現金,1.0,ふじヴィラ（熊本）宿泊,5.0,15400.0,NaN,熊本,2020/3/26,ふじヴィラ（熊本）宿泊への滞在手配です。ふじヴィラ（熊本）宿泊で贅沢な時間を
3,00017107,WVCPYZBH,2021/2/19,17100,False,NaN,カード,2.0,夢のようなの香港 4日間ツアー,3.0,7200.0,大阪,香港,2020/8/31,香港の魅力を存分に楽しめる4日間のツアー。夢のようなな体験を満喫し、心に残る旅を。
4,00024156,OELTJ7E2,2020/10/8,24100,True,23100.0,カード,1.0,魅惑のドバイ 5日間ツアー,3.0,24100.0,東京,ドバイ,2020/2/5,ドバイの魅力を存分に楽しめる5日間のツアー。魅惑の体験を満喫し、心に残る旅を。

In [5]:
# marged_dataの行数と列数を確認
merged_data.shape

(458167, 15)

In [6]:
# Transaction_historyとProduct_masterをproduct_idで結合（Right JOIN)し、marged_data2オブジェクトに格納
merged_data2 = transaction_history.merge(product_master, on="product_id", how="right")

In [7]:
# 結果の表示
merged_data2.head()

,customer_id,product_id,purchase_date,purchase_amount,redeem_coupon,final_settlement_amount,payment_method,purchase_channel,product_name,product_type,price,departure_city,destination_city,register_date,description
0,00010011,8RBQ8O3I,2021/7/27,72100.0,False,NaN,現金,1.0,リラックスできるニューヨーク 6日間ツアー,3,72100.0,福岡,ニューヨーク,2023/8/28,ニューヨークの魅力を存分に楽しめる6日間のツアー。リラックスできる体験を満喫し、心に残る旅を。
1,NaN,ZFQK59UL,NaN,NaN,NaN,NaN,NaN,NaN,ドキドキの香港 5日間ツアー,3,NaN,京都,香港,2023/12/24,香港の魅力を存分に楽しめる5日間のツアー。ドキドキな体験を満喫し、心に残る旅を。
2,00010014,5YH8O89R,2023/7/6,8500.0,True,8075.0,現金,4.0,ジャパンウィング航空 東京 → 高松 航空券,2,8500.0,東京,高松,2024/9/5,東京から高松へ、ジャパンウィング航空で快適な国内旅行を。お得な航空券で気軽に旅に出かけましょう。
3,00010016,MQTY8P6S,2019/10/21,286100.0,False,NaN,現金,2.0,贅沢なドバイ 6日間ツアー,3,286100.0,東京,ドバイ,2024/10/29,ドバイの魅力を存分に楽しめる6日間のツアー。贅沢な体験を満喫し、心に残る旅を。
4,NaN,1FKCUCHP,NaN,NaN,NaN,NaN,NaN,NaN,贅沢なドバイ 8日間ツアー,3,235000.0,京都,ドバイ,2023/5/13,ドバイの魅力を存分に楽しめる8日間のツアー。贅沢な体験を満喫し、心に残る旅を。

In [8]:
# marged_data2の行数と列数を確認
merged_data2.shape

(317999, 15)

In [9]:
# transaction_historyとProduct_masterをproduct_idで結合（innner join)し、marged_data3オブジェクトに格納
merged_data3 = transaction_history.merge(product_master, on="product_id", how="inner")

In [10]:
# 結果の表示
merged_data3.head()

,customer_id,product_id,purchase_date,purchase_amount,redeem_coupon,final_settlement_amount,payment_method,purchase_channel,product_name,product_type,price,departure_city,destination_city,register_date,description
0,00023085,G03257PD,2020/3/13,7200,True,6200.0,現金,2.0,サクラエアライン 東京 → バンコク 航空券（ビジネスクラス）,6,7200.0,東京,バンコク,2020/7/14,東京からバンコクまで、サクラエアラインのビジネスクラスで快適な空の旅を。上質なサービスで特別...
1,00015469,CKZF21ZC,2023/3/29,15400,False,NaN,カード,2.0,魅惑のローマ 6日間ツアー,3,15400.0,東京,ローマ,2023/3/13,ローマの魅力を存分に楽しめる6日間のツアー。魅惑の体験を満喫し、心に残る旅を。
2,00015482,7NSE0G0R,2023/12/26,15400,False,NaN,現金,1.0,ふじヴィラ（熊本）宿泊,5,15400.0,NaN,熊本,2020/3/26,ふじヴィラ（熊本）宿泊への滞在手配です。ふじヴィラ（熊本）宿泊で贅沢な時間を
3,00017107,WVCPYZBH,2021/2/19,17100,False,NaN,カード,2.0,夢のようなの香港 4日間ツアー,3,7200.0,大阪,香港,2020/8/31,香港の魅力を存分に楽しめる4日間のツアー。夢のようなな体験を満喫し、心に残る旅を。
4,00024156,OELTJ7E2,2020/10/8,24100,True,23100.0,カード,1.0,魅惑のドバイ 5日間ツアー,3,24100.0,東京,ドバイ,2020/2/5,ドバイの魅力を存分に楽しめる5日間のツアー。魅惑の体験を満喫し、心に残る旅を。

In [11]:
# marged_data3の行数と列数を確認
merged_data3.shape

(179991, 15)

In [12]:
# customer_idとdestination_city列を抽出
extracted_data = merged_data3[["customer_id", "destination_city"]]

In [13]:
# 結果の表示
extracted_data.head()

  customer_id destination_city
0    00023085             バンコク
1    00015469              ローマ
2    00015482               熊本
3    00017107               香港
4    00024156              ドバイ

In [14]:
# extracted_dataのcustomer_id別に、destination_Cityごとの出現回数をカウント（顧客別に、どの都市に何度訪れたかのクロス集計表）
# customer_idごとにdestination_cityの出現回数をカウントしdestination_countsオブジェクトに格納
destination_counts = (
    extracted_data.groupby("customer_id")["destination_city"]
    .value_counts()
    .unstack(fill_value=0)
)

# 結果の表示
destination_counts.head()

destination_city,アブダビ,シドニー,シンガポール,ソウル,ドバイ,ニューヨーク,バンコク,パリ,ロンドン,ローマ,...,旭川,松山,熊本,秋田,那覇,長崎,青森,静岡,香港,高松
customer_id,,,,,,,,,,,,,,,,,,,,,
00010000,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
00010001,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
00010002,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
00010003,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
00010004,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
# 顧客のアンケートデータををquestionary_dataというデータフレームに読み込み
import pandas as pd

questionary_data = pd.read_csv("../data/questionary_data.csv", dtype={"customer_id": str})

# 結果の表示
questionary_data.head()

,customer_id,date,annual_income,purpose_of_travel,travel_frequency,transport_flight,transport_train,transport_car_rental,transport_cruise,transport_other,...,travel_luxury_resort,travel_spa_relaxation,travel_activity_outdoor,travel_cultural_history,travel_cruise,travel_budget,info_email,info_social_media,info_storefront,info_phone_call
0,00009996,2018/1/10,4184000.0,0,0,NaN,1.0,NaN,1.0,NaN,...,1,1,0,0,1,1,0,1,0,0.0
1,00010000,NaN,20112000.0,2,0,NaN,1.0,1.0,NaN,NaN,...,1,0,1,0,0,1,0,1,0,1.0
2,00010056,2018/0/29,0.0,0,0,NaN,1.0,1.0,NaN,NaN,...,1,1,1,0,0,1,1,1,0,1.0
3,00010061,2018/2/6,0.0,2,0,NaN,1.0,1.0,NaN,NaN,...,1,1,1,0,0,1,0,1,0,0.0
4,00010098,2018/2/10,1104000.0,2,2,NaN,1.0,NaN,NaN,NaN,...,1,1,1,0,0,1,0,1,0,0.0

In [16]:
# 欠損値の確認
questionary_data.isnull().sum()

customer_id                   0
date                          1
annual_income               245
purpose_of_travel             0
travel_frequency              0
transport_flight           4572
transport_train             711
transport_car_rental       1031
transport_cruise           4807
transport_other            5035
travel_domestic               0
travel_international          0
travel_luxury_resort          0
travel_spa_relaxation         0
travel_activity_outdoor       0
travel_cultural_history       0
travel_cruise                 0
travel_budget                 0
info_email                    0
info_social_media             0
info_storefront               0
info_phone_call               4
dtype: int64

In [17]:
# questionary_dataオブジェクトのannual_income    の基本統計量を算出
questionary_data["annual_income"].describe()

count    4.805000e+03
mean     5.397937e+06
std      4.401559e+06
min      0.000000e+00
25%      2.108000e+06
50%      5.168000e+06
75%      8.126000e+06
max      2.919100e+07
Name: annual_income, dtype: float64

In [18]:
# qestionary_dataオブジェクトのannual_incomeの欠損値のセルに対し、annual_incomeの平均値を代入
# その後、代入したデータセットを作成し、qestionary_data2として格納し,表示する

# annual_incomeの平均値を計算
mean_annual_income = questionary_data["annual_income"].mean()

# annual_incomeの欠損値を平均値で補完
questionary_data2 = questionary_data.fillna({"annual_income": mean_annual_income})

# 結果を表示
questionary_data2.head()

,customer_id,date,annual_income,purpose_of_travel,travel_frequency,transport_flight,transport_train,transport_car_rental,transport_cruise,transport_other,...,travel_luxury_resort,travel_spa_relaxation,travel_activity_outdoor,travel_cultural_history,travel_cruise,travel_budget,info_email,info_social_media,info_storefront,info_phone_call
0,00009996,2018/1/10,4184000.0,0,0,NaN,1.0,NaN,1.0,NaN,...,1,1,0,0,1,1,0,1,0,0.0
1,00010000,NaN,20112000.0,2,0,NaN,1.0,1.0,NaN,NaN,...,1,0,1,0,0,1,0,1,0,1.0
2,00010056,2018/0/29,0.0,0,0,NaN,1.0,1.0,NaN,NaN,...,1,1,1,0,0,1,1,1,0,1.0
3,00010061,2018/2/6,0.0,2,0,NaN,1.0,1.0,NaN,NaN,...,1,1,1,0,0,1,0,1,0,0.0
4,00010098,2018/2/10,1104000.0,2,2,NaN,1.0,NaN,NaN,NaN,...,1,1,1,0,0,1,0,1,0,0.0

In [19]:
# 確認のため、qestionary_data2の欠損値を出力
questionary_data2.isnull().sum()

customer_id                   0
date                          1
annual_income                 0
purpose_of_travel             0
travel_frequency              0
transport_flight           4572
transport_train             711
transport_car_rental       1031
transport_cruise           4807
transport_other            5035
travel_domestic               0
travel_international          0
travel_luxury_resort          0
travel_spa_relaxation         0
travel_activity_outdoor       0
travel_cultural_history       0
travel_cruise                 0
travel_budget                 0
info_email                    0
info_social_media             0
info_storefront               0
info_phone_call               4
dtype: int64