In [1]:
# shop_masterを読み込みデータを表示します。
import pandas as pd

shop_master = pd.read_csv("../data/shop_master.csv")
shop_master.head()

   shop_id       zip   shop_name            address    Latitude    Longitude
0  S000001  053-8722  北海道　苫小牧出張所     北海道苫小牧市旭町4-5-6  42°38′03″N  141°36′20″E
1  S000002  154-8504     東京　成城支店  東京都世田谷区世田谷4-21-27  35°38′48″N  139°39′12″E
2  S000003  105-8511    東京　白金台支店     東京都港区芝公園1-5-25  35°38′48″N  139°43′22″E
3  S000004  400-8585    山梨県　甲府支店    山梨県甲府市丸の内1-18-1  35°39′44″N  138°34′06″E
4  S000005     75001   フランス　パリ支店            フランス パリ  48°51′24″N     2°21′3″E

In [2]:
# データ型の確認をしてみましょう
print(shop_master.dtypes)

shop_id      object
zip          object
shop_name    object
address      object
Latitude     object
Longitude    object
dtype: object

In [3]:
# LatitudeとLongitudeを十進法に変換します。
def convert_dms_to_dd(dms_str):
    """
    度分秒(DMS)形式の文字列を十進法(DD)に変換する関数、dms_strを用います。
    度分秒形式の文字列（例: '35°41′23″N'）を渡すと、十進法で表現された緯度または経度に変換し、変換できない場合は元の文字列を返します。"""

    try:
        parts = dms_str.split("°")
        degrees = float(parts[0])
        minutes_part = parts[1].split("′")
        minutes = float(minutes_part[0])
        seconds_part = minutes_part[1].split("″")
        seconds = float(seconds_part[0])

        direction = seconds_part[1]  # N, S, E, W

        dd = degrees + (minutes / 60) + (seconds / 3600)
        if direction in ("S", "W"):
            dd *= -1
        return dd

    except (IndexError, ValueError):
        return dms_str  # 変換できない場合は元の値を返す


# 緯度と経度の列名を確認し、必要があれば修正
# shop_master.columnsで列名を確認できます。
# 例：列名が'Latitude'と'Longitude'の場合
latitude_column = "Latitude"  # 'latitude'を実際の列名に置き換える
longitude_column = "Longitude"  # 'longitude'を実際の列名に置き換える

# 緯度と経度の列を十進法に変換
shop_master["latitude_dd"] = shop_master[latitude_column].apply(convert_dms_to_dd)
shop_master["longitude_dd"] = shop_master[longitude_column].apply(convert_dms_to_dd)

shop_master.head()

,shop_id,zip,shop_name,address,Latitude,Longitude,latitude_dd,longitude_dd
0,S000001,053-8722,北海道 苫小牧出張所,北海道苫小牧市旭町4-5-6,42°38′03″N,141°36′20″E,42.634167,141.605556
1,S000002,154-8504,東京 成城支店,東京都世田谷区世田谷4-21-27,35°38′48″N,139°39′12″E,35.646667,139.653333
2,S000003,105-8511,東京 白金台支店,東京都港区芝公園1-5-25,35°38′48″N,139°43′22″E,35.646667,139.722778
3,S000004,400-8585,山梨県 甲府支店,山梨県甲府市丸の内1-18-1,35°39′44″N,138°34′06″E,35.662222,138.568333
4,S000005,75001,フランス パリ支店,フランス パリ,48°51′24″N,2°21′3″E,48.856667,2.350833